### ISSUE TITLE
[JOSS] Naming conventions, constructors

### ISSUE THREAD

**Issue by matbesancon** [kirui93/ScenTrees.jl#9]
Following Julia style guide, functions should use `snake_case()` with underscores, while types, like `struct`s, should use CamelCase beginning with an upper-case.

**Comment by matbesancon** [comment]
The `Children(parent::Vector{Int64})` should maybe not be in the constructor of Tree but appart, it looks like a constructor when it is not

**Comment by matbesancon** [comment]
The `Tree(identifier::Int64)` constructor should not be a constructor in itself, since it builds examples, this is only due to `Children` being an internal function of Tree.

**Comment by matbesancon** [comment]
Linking to the review: https://github.com/openjournals/joss-reviews/issues/1912

**Comment by kirui93** [comment]
The function `Children(parent::Vector{Int64})` is a very important function in the constructor. With the stochastic approximation process that we are using to generate scenario trees, we are accessing the children so many times at each iteration. Therefore, we preferred to have all the children of the parent nodes initially before the iteration so that we can only be accessing them by index.

The structure of the constructors here suits best to our procedures especially stochastic approximation process.

**Comment by matbesancon** [comment]
Overall, there is still work on this issue, lots of functions have a `CamelCase` syntax, while this should be for modules and types, while functions should be in `snake_case`

**Comment by matbesancon** [comment]
Same thing with `buildProb!` `partTree`

**Comment by kirui93** [comment]
In this case therefore, I will need to re-write the whole package including also the documentation.

**Comment by matbesancon** [comment]
no need to re-write, just search-and-replace the old names with the new names. If you are afraid of breaking the code of current users, you can use the `@deprecate` macro

**Comment by kirui93** [comment]
That is what am doing currently. My point was that I need to replace also in the documentation to match the current naming.

**Comment by matbesancon** [comment]
yes no problem

**Comment by kirui93** [comment]
I think this is perfect now.

**Comment by matbesancon** [comment]
yes we can close it perfect
